name: CI

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 
              uses: actions/setup-python@v4
              with:
                  python-version: '3.x'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pytest-playwright
                  pip install exceptiongroup
                  playwright install chromium
                  pip install allure-pytest
              continue-on-error: true
            - name: Run tests
              run: pytest
              continue-on-error: true        
            - name: Allure Report action from marketplace
              uses: simple-elf/allure-report-action@master
              if: always()
              #id: allure-report
              with:
                allure_results: reports
                #gh_pages: gh-pages
                #allure_report: allure-report
                allure_history: allure-history
                keep_reports: 20
            - name: Deploy report to Github Pages
              if: always()
              uses: peaceiris/actions-gh-pages@v2
              env:
               PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
               PUBLISH_BRANCH: gh-pages
               PUBLISH_DIR: allure-history
