name: CI

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4.7.0
              with:
                  python-version: '3.x'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pipenv
                  pip install exceptiongroup
                  pip install playwright
                  pip install pytest-playwright
                  playwright install chromium
                  pipenv install allure-pytest
              continue-on-error: true
            - name: Run tests
              run: pytest
